spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/UtnPhones?allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: development
    password: development1